// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-open-tickets.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_open_tickets_default = defineTool({
  name: "list_open_tickets",
  title: "List open tickets",
  description: "List open (non-closed) support tickets visible to the signed-in user, ordered by most recently updated.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("Maximum number of tickets to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("tickets").select("id, title, status, priority, client_id, created_at, updated_at").not("status", "in", "(closed,resolved,cancelled)").order("updated_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { tickets: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-ticket.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_ticket_default = defineTool2({
  name: "get_ticket",
  title: "Get ticket details",
  description: "Fetch a single support ticket by ID, including comments.",
  inputSchema: {
    ticketId: z2.string().uuid().describe("The ticket UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ ticketId }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    const { data: ticket, error } = await sb.from("tickets").select("*").eq("id", ticketId).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!ticket) return { content: [{ type: "text", text: "Ticket not found" }], isError: true };
    const { data: comments } = await sb.from("ticket_comments").select("id, content, created_at, user_id, is_internal").eq("ticket_id", ticketId).order("created_at", { ascending: true });
    const payload = { ticket, comments: comments ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/search-clients.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_clients_default = defineTool3({
  name: "search_clients",
  title: "Search clients",
  description: "Search clients by name or CNPJ. Returns clients visible to the signed-in user.",
  inputSchema: {
    query: z3.string().trim().min(1).describe("Text to match against client name or CNPJ."),
    limit: z3.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const like = `%${query.replace(/[%_]/g, "")}%`;
    const { data, error } = await supabaseForUser3(ctx).from("clients").select("id, name, cnpj, email, phone, is_active").or(`name.ilike.${like},cnpj.ilike.${like}`).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-active-contracts.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_active_contracts_default = defineTool4({
  name: "list_active_contracts",
  title: "List active contracts",
  description: "List active contracts, optionally filtered by client ID.",
  inputSchema: {
    clientId: z4.string().uuid().optional().describe("Optional client UUID to filter contracts."),
    limit: z4.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ clientId, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser4(ctx).from("contracts").select("id, client_id, contract_number, monthly_value, status, start_date, end_date").eq("status", "active").order("start_date", { ascending: false }).limit(limit);
    if (clientId) query = query.eq("client_id", clientId);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { contracts: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "silefpsayliwqtoskkdz";
var mcp_default = defineMcp({
  name: "colmeia-mcp",
  title: "Colmeia \u2014 Central de Suporte",
  version: "0.1.0",
  instructions: "Ferramentas do sistema Colmeia (MSP): consultar chamados abertos, ver detalhes de um chamado, buscar clientes e listar contratos ativos. Todas as chamadas rodam como o usu\xE1rio conectado, respeitando as permiss\xF5es (RLS) da conta.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_open_tickets_default, get_ticket_default, search_clients_default, list_active_contracts_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
